project:
  type: default
  output-dir: outputs

execute:
  freeze: auto

format:
  html:
    toc: true
    number-sections: true

  docx:
    toc: true
    number-sections: true

  pdf:
    toc: true
    number-sections: true